import pandas as pd

def load_product_database():
    """Load comprehensive product database with ingredients and recommendations"""
    products_data = [
        {
            'id': 1,
            'name': 'SkinCeuticals C E Ferulic',
            'brand': 'SkinCeuticals',
            'category': 'Serum',
            'price': 169,
            'ingredients': 'Vitamin C, Vitamin E, Ferulic Acid, L-Ascorbic Acid',
            'skin_concerns': 'UV damage, aging, dullness, sun spots',
            'skin_type': 'all',
            'rating': 4.8,
            'reviews': 1250,
            'amazon_link': 'https://www.amazon.com/',
            'search_query': 'SkinCeuticals C E Ferulic Vitamin C Serum',
            'image_url': 'https://placehold.co/150x150',
            'key_benefits': ['UV damage repair', 'Antioxidant protection', 'Brightening'],
            'usage': 'Morning after cleansing, before moisturizer'
        },
        {
            'id': 2,
            'name': "Paula's Choice SKIN PERFECTING 2% BHA Liquid Exfoliant",
            'brand': "Paula's Choice",
            'category': 'Exfoliant',
            'price': 32,
            'ingredients': 'Salicylic Acid, Green Tea Extract, BHA',
            'skin_concerns': 'acne, blackheads, large pores, oily skin',
            'skin_type': 'oily, combination, acne-prone',
            'rating': 4.6,
            'reviews': 8900,
            'amazon_link': 'https://www.amazon.com/',
            'search_query': 'Paulas Choice 2% BHA Liquid Exfoliant Salicylic Acid',
            'image_url': 'https://placehold.co/150x150',
            'key_benefits': ['Acne treatment', 'Pore cleansing', 'Gentle exfoliation'],
            'usage': 'Evening, 2-3 times per week initially'
        },
        {
            'id': 3,
            'name': 'The Ordinary Hyaluronic Acid 2% + B5',
            'brand': 'The Ordinary',
            'category': 'Serum',
            'price': 8,
            'ingredients': 'Hyaluronic Acid, Vitamin B5, Sodium Hyaluronate',
            'skin_concerns': 'dryness, dehydration, fine lines, rough texture',
            'skin_type': 'dry, normal, dehydrated',
            'rating': 4.4,
            'reviews': 15600,
            'amazon_link': 'https://www.amazon.com/',
            'search_query': 'The Ordinary Hyaluronic Acid 2% B5 Serum',
            'image_url': 'https://placehold.co/150x150',
            'key_benefits': ['Intense hydration', 'Plumping effect', 'Smooth texture'],
            'usage': 'Morning and evening, apply to damp skin'
        },
        {
            'id': 4,
            'name': 'Neutrogena Ultra Sheer Dry-Touch SPF 100+',
            'brand': 'Neutrogena',
            'category': 'Sunscreen',
            'price': 12,
            'ingredients': 'Avobenzone, Homosalate, Octisalate, Octocrylene',
            'skin_concerns': 'UV protection, sun damage prevention, daily protection',
            'skin_type': 'all',
            'rating': 4.3,
            'reviews': 5400,
            'amazon_link': 'https://www.amazon.com/',
            'search_query': 'Neutrogena Ultra Sheer Dry Touch SPF 100 Sunscreen',
            'image_url': 'https://placehold.co/150x150',
            'key_benefits': ['Broad spectrum protection', 'Non-greasy', 'Water resistant'],
            'usage': 'Morning, reapply every 2 hours'
        },
        {
            'id': 5,
            'name': 'LilyAna Naturals Retinol Cream Moisturizer',
            'brand': 'LilyAna Naturals',
            'category': 'Moisturizer',
            'price': 25,
            'ingredients': 'Retinol, Hyaluronic Acid, Vitamin E, Jojoba Oil',
            'skin_concerns': 'aging, wrinkles, fine lines, firmness',
            'skin_type': 'mature, normal, aging',
            'rating': 4.5,
            'reviews': 3200,
            'amazon_link': 'https://www.amazon.com/',
            'search_query': 'LilyAna Naturals Retinol Cream Moisturizer Anti Aging',
            'image_url': 'https://placehold.co/150x150',
            'key_benefits': ['Anti-aging', 'Wrinkle reduction', 'Skin renewal'],
            'usage': 'Evening only, start 2x per week'
        },
        {
            'id': 6,
            'name': 'CeraVe Hydrating Facial Cleanser',
            'brand': 'CeraVe',
            'category': 'Cleanser',
            'price': 15,
            'ingredients': 'Ceramides, Hyaluronic Acid, MVE Technology',
            'skin_concerns': 'gentle cleansing, dryness, sensitive skin',
            'skin_type': 'dry, normal, sensitive',
            'rating': 4.7,
            'reviews': 12000,
            'amazon_link': 'https://www.amazon.com/',
            'search_query': 'CeraVe Hydrating Facial Cleanser Ceramides Hyaluronic Acid',
            'image_url': 'https://placehold.co/150x150',
            'key_benefits': ['Gentle cleansing', 'Moisture retention', 'Barrier support'],
            'usage': 'Morning and evening'
        },
        {
            'id': 7,
            'name': 'The Ordinary Niacinamide 10% + Zinc 1%',
            'brand': 'The Ordinary',
            'category': 'Serum',
            'price': 7,
            'ingredients': 'Niacinamide, Zinc PCA',
            'skin_concerns': 'oily skin, large pores, blemishes, uneven tone',
            'skin_type': 'oily, combination, acne-prone',
            'rating': 4.3,
            'reviews': 25000,
            'amazon_link': 'https://www.amazon.com/',
            'search_query': 'The Ordinary Niacinamide 10% Zinc 1% Serum Pores',
            'image_url': 'https://placehold.co/150x150',
            'key_benefits': ['Oil control', 'Pore minimizing', 'Blemish reduction'],
            'usage': 'Morning and evening before oils/moisturizers'
        },
        {
            'id': 8,
            'name': 'Olay Regenerist Micro-Sculpting Cream',
            'brand': 'Olay',
            'category': 'Moisturizer',
            'price': 19,
            'ingredients': 'Amino-Peptides, Glycerin, Isopropyl Isostearate',
            'skin_concerns': 'aging, wrinkles, firmness, hydration',
            'skin_type': 'mature, dry, normal',
            'rating': 4.4,
            'reviews': 8500,
            'amazon_link': 'https://www.amazon.com/',
            'search_query': 'Olay Regenerist Micro Sculpting Face Moisturizer Anti Aging',
            'image_url': 'https://placehold.co/150x150',
            'key_benefits': ['Firming', 'Anti-aging', 'Deep moisturizing'],
            'usage': 'Morning and evening'
        },
        {
            'id': 9,
            'name': 'Aveeno Daily Moisturizing Lotion',
            'brand': 'Aveeno',
            'category': 'Moisturizer',
            'price': 8,
            'ingredients': 'Colloidal Oatmeal, Glycerin, Petrolatum',
            'skin_concerns': 'dryness, sensitivity, irritation, rough skin',
            'skin_type': 'dry, sensitive, normal',
            'rating': 4.6,
            'reviews': 15000,
            'amazon_link': 'https://www.amazon.com/',
            'search_query': 'Aveeno Daily Moisturizing Lotion Colloidal Oatmeal',
            'image_url': 'https://placehold.co/150x150',
            'key_benefits': ['24-hour hydration', 'Gentle formula', 'Sensitive skin safe'],
            'usage': 'Morning and evening'
        },
        {
            'id': 10,
            'name': 'Differin Adapalene Gel 0.1%',
            'brand': 'Differin',
            'category': 'Treatment',
            'price': 13,
            'ingredients': 'Adapalene, Carbomer 940, Phenoxyethanol',
            'skin_concerns': 'acne, blackheads, comedones, oily skin',
            'skin_type': 'acne-prone, oily',
            'rating': 4.2,
            'reviews': 7800,
            'amazon_link': 'https://www.amazon.com/',
            'search_query': 'Differin Adapalene Gel 0.1% Acne Treatment Retinoid',
            'image_url': 'https://placehold.co/150x150',
            'key_benefits': ['Acne treatment', 'Prevents breakouts', 'FDA approved'],
            'usage': 'Evening only, once daily'
        }
    ]
    
    return pd.DataFrame(products_data)
